files:
  - source: /**/messages.properties
    translation: >-
      %original_path%/messages_%two_letters_code%.properties
    update_option: update_without_changes
commit_message: 'New translations: %original_file_name% (%language%)'
append_commit_message: false
