#------------------------------------------------------------------------------------
# Github Action to generate Checkstyle site.
#
# Workflow starts when:
# 1) issue comment - created, edited
#
# Requirements:
# 1) secrets.AWS_ACCESS_KEY_ID - access key for AWS S3 service user
# 2) secrets.AWS_SECRET_ACCESS_KEY - security access key for AWS S3 service user
#
# If you need to change bucket name or region, change AWS_REGION and AWS_BUCKET_NAME variables.
# For another bucket, you will need to change the secrets.
#------------------------------------------------------------------------------------
name: Site
env:
  AWS_REGION: us-east-2
  AWS_BUCKET_NAME: "checkstyle-diff-reports"
on:
  push:
    branches: [master]

jobs:
  parse_pr_info:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          mvn --version
